---
title: "Aggregate Human Coding of MAPS Data"
author: "Paul Alexander Bloom"
date: "2025-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
source('helper_functions.R')
```

# MAPS

## Combine coder files and coalesce together
```{r}
# Step 1: Combine the coder files
file_paths = list.files("/Volumes/AUERBACHLAB/Columbia/MAPS_Language/data/manual_coding/suicide_language/step_one_coding/coded_reconverted_csvs/", 
                        pattern = "\\.csv$", full.names = TRUE)

combined_data = combine_coder_files(file_paths, unique_col_name = "suicide_related")

# Step 2: Coalesce using key file
coalesced = coalesce_coder_columns(combined_data, coder_key_path = "../coding manuals/step_1_coding_delegation.csv")
coalesced = coalesced %>%
  mutate(
    code1 = replace_na(code1, 0),
    code2 = replace_na(code2, 0)
  )

# Check agreement statistics
agreement_check =  coalesced%>%
  group_by(subjectID, coder1_name, coder2_name) %>%
  summarise(n=n(), 
            coder1_positive = sum(code1==1),
            coder2_positive = sum(code2==1),
            agreed_positive = sum(code1==1 & code2 ==1),
            agreed = sum(code1==code2),
            disagreed = sum(code1!=code2),
            agree_prop = agreed/n)

# Find entries where coders disagree
disagree_rows = dplyr::filter(coalesced, code1 != code2)

agree_rows = dplyr::filter(coalesced, code1 == code2, code1==1)
```

## Calculate cohen's kappa by subject

```{r}
kappa_by_subject = coalesced %>%
  select(subjectID, code1, code2) %>%
  group_by(subjectID) %>%
  group_map(~ {
    df = .x %>% select(code1, code2) %>% drop_na()
    if (nrow(df) == 0) {
      tibble(subjectID = .y$subjectID, kappa = NA_real_)
    } else {
      kappa_val = psych::cohen.kappa(as.matrix(df))$kappa
      tibble(subjectID = .y$subjectID, kappa = kappa_val)
    }
  }) %>%
  bind_rows()

```


## Overall Kappa for MAPS

```{r}
data_for_kappa = coalesced %>% dplyr::select(code1, code2) %>% ungroup() 
kappa_mat = as.matrix(data_for_kappa)
psych::cohen.kappa(x=kappa_mat)


# percent agreement
100*sum(coalesced$code1==coalesced$code2) / nrow(coalesced)
```


## Save out rows of disagreement for 3rd coder
```{r}
disagree_rows_for_coder3 = disagree_rows %>% 
  dplyr::select(subjectID, tm_message_start, tm_message_end, 
                timeDiff, id_app, text_clean)

disagree_rows_for_coder3$code3 = ''

write.csv(disagree_rows_for_coder3, file = paste0('/Volumes/AUERBACHLAB/Columbia/MAPS_Language/data/manual_coding/suicide_language/step_one_coding/to_review/disagreement_rows_for_coder3_', Sys.Date(), '.csv'))
```


## Pull in coder3 ratings to break ties

```{r}
# Step 1: Read and process coder3_ratings
coder3_ratings <- read_csv("../../../data/manual_coding/suicide_language/step_one_coding/to_review/disagreement_rows_for_coder3_2025-05-06.csv") %>%
  select(subjectID, tm_message_start, tm_message_end, id_app, text_clean, code3) %>%
  mutate(
    tm_message_startj = mdy_hm(tm_message_start, tz = "UTC"),
    tm_message_endj   = mdy_hm(tm_message_end, tz = "UTC")
  ) %>%
  dplyr::select(-tm_message_start, -tm_message_end)

# Step 2: Process final_codings (coalesced), keeping full timestamps
final_codings <- coalesced %>%
  ungroup() %>%
  mutate(
    tm_message_startj = floor_date(ymd_hms(tm_message_start, tz = "UTC"), unit = "minute"),
    tm_message_endj   = floor_date(ymd_hms(tm_message_end, tz = "UTC"), unit = "minute")
  )

# Step 3: Join on truncated timestamps
final_codings <- left_join(final_codings,
                           coder3_ratings,
                           by = c("subjectID", "tm_message_startj", "tm_message_endj", "id_app", "text_clean"))



sum(!is.na(final_codings$code3))

# Use coder3 to resolve coding disagreements as tiebreaker
final_codings = final_codings %>%
  mutate(suicide_related = 
           case_when(code1 == code2 ~ code1,
                     code1 != code2 & !is.na(code3) ~ code3,
                     code1 != code2 & is.na(code3) ~ 1
           ))

c = dplyr::filter(final_codings, code1!=code2)

final_codings = final_codings %>%
  dplyr::select(-contains('code'), -tm_message_startj, -tm_message_endj)


write.csv(final_codings, file = '../../../data/manual_coding/suicide_language/step_one_coding/coded_reconverted_csvs/final/final_codings.csv', row.names = FALSE)
```


# PREDICT

```{r}
coalesced_predict = merge_coder_files_predict(
  data_dir  = "/Volumes/AUERBACHLAB/Columbia/MAPS_Language/data/manual_coding/suicide_language_prediction/predict_coding_stage1/completed",
  join_cols = c("subjectID", "entry_id", "tm_message_start", "tm_message_end", "id_app", "text_clean", "translated_message"),
  make_temporary = FALSE
)


coalesced_doublecode_predict = coalesced_predict$paired

# replace NAs (which indicate absence of suicide-related language in coding) with 0s
coalesced_doublecode_predict = coalesced_doublecode_predict %>%
  mutate(
    suicide_related_coder1 = replace_na(suicide_related_coder1, 0),
    suicide_related_coder2 = replace_na(suicide_related_coder2, 0)
  )
```

## Full kappa for all coded data

```{r}
data_for_kappa_predict = coalesced_doublecode_predict %>% dplyr::select(suicide_related_coder1, suicide_related_coder2) %>% ungroup() 

full_data_for_kappa = rbind(data_for_kappa_predict %>% dplyr::select(code1=suicide_related_coder1, code2=suicide_related_coder2),
                            data_for_kappa)

full_kappa_mat = as.matrix(full_data_for_kappa)
psych::cohen.kappa(x=full_kappa_mat)

```

## For resolving ties
```{r}

coalesced_doublecode_predict = dplyr::mutate(coalesced_doublecode_predict, disagree = ifelse(suicide_related_coder1 != suicide_related_coder2, 1, 0))


disagree_rows =  dplyr::filter(coalesced_doublecode_predict, disagree==1) %>%
  dplyr::select(subjectID, entry_id, disagree)

disagree_rows %>%
  group_by(subjectID) %>%
  count()

write.csv(disagree_rows, file = '../../../data/manual_coding/suicide_language_prediction/predict_coding_stage1/disagreement_delegation.csv', row.names=FALSE)

# write out individual csv files for coder3 to resolve (masking who coded what prior)
for (id in unique(coalesced_doublecode_predict$subjectID)){
  outdata = dplyr::filter(coalesced_doublecode_predict, subjectID==id)
  outdata = dplyr::select(outdata, -coder1_name, -coder2_name, -suicide_related_coder1, -suicide_related_coder2)
  outdata$coder3 = ''
  write.csv(outdata, file = paste0('../../../data/manual_coding/suicide_language_prediction/predict_coding_stage1/disagreement_blank/', id, '_blank.csv'), row.names=FALSE)
}

```

## Pull in disagreement files (tie-breaking)
```{r}
disagreement_files = list.files('../../../data/manual_coding/suicide_language_prediction/predict_coding_stage1/disagreement_completed/',
                                pattern = '.csv', 
                                full.names = TRUE)


disagreement_resolution = map_dfr(disagreement_files, read_csv, col_types = cols(
  tm_message_start = col_character(),
  tm_message_end = col_character()
))

disagreement_resolution = dplyr::filter(disagreement_resolution, disagree==1)


final_predict = left_join(coalesced_doublecode_predict, dplyr::select(disagreement_resolution, subjectID, entry_id, coder3),
                          by = c('subjectID', 'entry_id'))



final_predict = mutate(final_predict,
                       suicide_related = case_when(
                         disagree == 0 ~ suicide_related_coder1,
                         disagree == 1 & !is.na(coder3) ~ coder3
                       ))


final_predict = dplyr::select(final_predict, -subjectID, -contains('coder'))

# Write out for model validation
save(final_predict, file = '../model_outputs_step1/coder_labels_predict_stage1_coalesced.rda')
write.csv(final_predict, file = '../model_outputs_step1/coder_labels_predict_stage1_coalesced.csv', row.names=FALSE)
```
