---
title: 'Validate Youth Suicide Lexicon, LLM, and Existing Lexicons'
author: "Paul Alexander Bloom"
date: "2025-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(caret)
library(ggplot2)
library(stringr)
library(cowplot)
source('helper_functions.R')
```

# Load MAPS validation dataframe
```{r}
combined_validation_df = read_csv('../model_outputs_step1/maps_predict_validation_combined.csv')
```

# Bootstrap model performance metrics in MAPS 5% data

```{r}
combined_validation_df = mutate(combined_validation_df, 
                                lexicon_only_flag = ifelse(is.na(lexicon_only_flag), 0, lexicon_only_flag))


# gpt-code column is GPT-4o mini


performance_metrics_combined = bootstrap_evaluate_predictions(
  full_df = combined_validation_df,
  reference_col = "suicide_related",
  prediction_cols = c( 'lexicon_only_flag', 
                                                                'swaminathan_full_flag',
                                                                'swaminathan_thoughtsmethods_flag',
                                                                'low_srl_flag', 
                                                                'low_srl_flag_count_only',
                                                                'gpt_code',
                                                                'gpt3_code'),
  positive_class = '1',
  n_iterations = 100)
```

```{r}
performance_metrics_combined_all = performance_metrics_combined %>% mutate(PredictionColumn = dplyr::recode(PredictionColumn,
                                         'low_srl_flag'='Low 2024 Lexicon (Exact+Similarity)',
                                         'low_srl_flag_count_only'='Low 2024 Lexicon (Exact)',
                                         'lexicon_only_flag'='Youth Suicide Lexicon',
                                         'swaminathan_full_flag'='Swaminathan 2023 Lexicon (Full)',
                                         'swaminathan_thoughtsmethods_flag'='Swaminathan 2023 Lexicon (Suicide Thoughts/Methods)',
                                         'gpt_code'='gpt'),
                                         'gpt3_code'='gpt3')
# only spellchecked for main figure
performance_metrics_combined = performance_metrics_combined %>% mutate(PredictionColumn = dplyr::recode(PredictionColumn,
                                         'low_srl_flag'='Low 2024 Lexicon (Exact+Similarity)',
                                         'lexicon_only_flag'='Youth Suicide Lexicon',
                                         'swaminathan_thoughtsmethods_flag'='Swaminathan 2023 Lexicon (Suicide Thoughts/Methods)',
                                         'gpt_code'='gpt',
                                         'gpt3_code'='gpt3')
                                         ) %>%
  dplyr::filter(!grepl('_', PredictionColumn))


# Summarize
performance_metrics_summary_combined <- performance_metrics_combined %>%
  pivot_longer(cols = c('Precision', 'Recall', 'F1', 'Sensitivity', 'Specificity', 'Balanced_Accuracy'), 
               names_to = "Metric", 
               values_to = "Value") %>%
  group_by(PredictionColumn, Metric) %>%
  summarise(mean = mean(Value),
            lwr95 = quantile(Value, .025),
            upr95 = quantile(Value, .975))

# Order by F1
f1_order_combined <- performance_metrics_summary_combined %>%
  dplyr::filter(Metric =='F1') %>%
  arrange(desc(mean)) %>%
  pull(PredictionColumn)

performance_metrics_summary_combined = mutate(performance_metrics_summary_combined, 
                                          is_youth_srl = ifelse(grepl('Youth', PredictionColumn), 'y', 'n'))

performance_metrics_summary_combined_F1 =performance_metrics_summary_combined

performance_metrics_summary_combined_F1$PredictionColumn = factor(performance_metrics_summary_combined$PredictionColumn, levels = f1_order_combined)


# True positives/base rate
combined_true_positives_n = sum(combined_validation_df$suicide_related)
combined_true_base_rate = round(100* sum(combined_validation_df$suicide_related) / nrow(combined_validation_df), 2)

gpt_false_negatives = dplyr::filter(combined_validation_df, gpt_code == 0 & suicide_related == 1)
gpt_false_positives = dplyr::filter(combined_validation_df, gpt_code == 1 & suicide_related == 0)

```


```{r}
# Define once, use in both plots
method_colors <- c(
  'GPT-4o mini (Few-shot)'     = 'black',
  'Low 2024 Lexicon'           = '#d55e00',
  'Swaminathan 2023 Lexicon'   = '#3DB7E9',
  'Youth Suicide Lexicon'      = '#359B73'
)


step1_fig_combined_small = performance_metrics_summary_combined_F1 %>%
  dplyr::filter(Metric %in% c('F1', 'Recall', 'Precision'),
                PredictionColumn %in% c('Youth Suicide Lexicon', 'Low 2024 Lexicon (Exact+Similarity)', 'Swaminathan 2023 Lexicon (Suicide Thoughts/Methods)', 'gpt')) %>%
    mutate(PredictionColumn = dplyr::recode(PredictionColumn,
                                          'gpt'='GPT-4o mini (Few-shot)',
                                          'gpt3'='GPT3.5-turbo (Few-shot)',
                                         'Low 2024 Lexicon (Exact+Similarity)'='Low 2024 Lexicon',
                                         'Swaminathan 2023 Lexicon (Suicide Thoughts/Methods)'='Swaminathan 2023 Lexicon'),
           Metric = dplyr::recode(Metric, 'Recall'='Recall (Sensitivity)', 
                                          'Precision'='Precision (Positive Predictive Value)')) %>%
  ggplot(aes(y = PredictionColumn, x = mean)) +
  geom_point(aes(color = PredictionColumn)) +
  geom_errorbarh(aes(xmin = lwr95, xmax = upr95, color = PredictionColumn), height = 0.1) +
  geom_line(aes(group = PredictionColumn)) +
  facet_grid(cols = vars(Metric)) +
  theme_bw() +
  labs(x = "Score", y=NULL, 
       title = paste0('\nValidation Participants (N=', length(unique(combined_validation_df$subjectID)), ') from MAPS & PREDICT Cohorts (Higher-Risk Adolescents)'),
       subtitle = paste0("N=", nrow(combined_validation_df), ' labeled text entries with ', 
                         combined_true_positives_n, ' true positives (Base rate ',
                         combined_true_base_rate, '%)')) +
  theme(legend.position = 'none',
       text=element_text(face = 'bold')) +
  xlim(0,1) + 
  theme(plot.background = element_rect(color = "black")) +
  scale_color_manual(values = method_colors)


ggsave(step1_fig_combined_small, filename = '../figures/main/rev1/figure1_validation_maps_predict.png',
       height = 4, width = 10)

```


# PED-SI Validation


PED-SI = Data from WashU
```{r}
load('../model_outputs_step1/data_for_washu_validation.rda')


# Check & prep data
length(unique(washu_for_validation$subjectID))

# Check base rates
sum(washu_for_validation$SI, na.rm = TRUE)

counts = washu_for_validation %>%
  group_by(filepath) %>%
  summarise(n= n(),
            total_si = sum(SI),
            si_rate = total_si/n)

# Code outcome variables
washu_for_validation = mutate(washu_for_validation, 
                  `Youth SRL+`=ifelse(youth_suicide_lexicon_tokens ==1 |
                                       youth_suicide_lexicon_celeb ==1 |
                                       emoji_flag ==1 |
                                       youth_suicide_lexicon_pairs ==1, 1, 0),
                  `Youth SRL`=ifelse(youth_suicide_lexicon_tokens ==1 |
                                       youth_suicide_lexicon_pairs ==1, 1, 0),
                  )

```

# Washu data on false negatives/true positives/ base rate
```{r}
washu_falseneg = dplyr::filter(washu_for_validation, 
                               SI==1,
                               `Youth SRL+`==0)


washu_true_positives_n = sum(washu_for_validation$SI)
washu_true_base_rate = round(100* sum(washu_for_validation$SI) / nrow(washu_for_validation), 2)
```

# Boostrap model performance for WashU Data
```{r}
performance_metrics_washu = bootstrap_evaluate_predictions(
  full_df = washu_for_validation,
  reference_col = "SI",
  prediction_cols = c('Youth SRL', 'Youth SRL+', 'suicide_lexicon_swaminathan_2023', 'suicide_lexicon_swaminathan_2023_thoughts_methods_only',
                      'low_srl_flag', 'low_srl_flag_count_only'),
  positive_class = '1',
  n_iterations = 100
)

```

# Summarize and Plot WashU Model Performance Stats
```{r}
performance_metrics_summary_washu <- performance_metrics_washu %>%
  pivot_longer(cols = c('Precision', 'Recall', 'F1', 'Sensitivity', 'Specificity', 'Balanced_Accuracy'), 
               names_to = "Metric", 
               values_to = "Value") %>%
  group_by(PredictionColumn, Metric) %>%
  summarise(mean = mean(Value),
            lwr95 = quantile(Value, .025),
            upr95 = quantile(Value, .975))

performance_metrics_summary_washu = mutate(performance_metrics_summary_washu, 
                                           PredictionColumn = dplyr::recode(PredictionColumn,
                                          'low_srl_flag'='Low 2024 Lexicon (Exact+Similarity)',
                                         'low_srl_flag_count_only'='Low 2024 Lexicon (Exact)',
                                          'Youth SRL'='Youth Suicide Lexicon',    
                                          'Youth SRL+'='Youth Suicide Lexicon (+Emojis, Celebrity/Historical Suicides)', 
                                         'suicide_lexicon_swaminathan_2023'='Swaminathan 2023 Lexicon (Full)',
                                         'suicide_lexicon_swaminathan_2023_thoughts_methods_only'='Swaminathan 2023 Lexicon (Suicide Thoughts/Methods)')
                                         )

# For ordering plots by F1
f1_order_washu <- performance_metrics_summary_washu %>%
  dplyr::filter(Metric =='F1') %>%
  arrange(desc(mean)) %>%
  pull(PredictionColumn)


performance_metrics_summary_washu = mutate(performance_metrics_summary_washu, 
                                          is_youth_srl = ifelse(grepl('Youth', PredictionColumn), 'y', 'n'))

performance_metrics_summary_washu_F1 =performance_metrics_summary_washu

performance_metrics_summary_washu_F1$PredictionColumn = factor(performance_metrics_summary_washu$PredictionColumn, levels = f1_order_washu)


step1_fig_pedsi_small = performance_metrics_summary_washu_F1 %>%
  dplyr::filter(Metric %in% c('F1', 'Recall', 'Precision'),
                PredictionColumn %in% c('Youth Suicide Lexicon', 'Low 2024 Lexicon (Exact)', 'Swaminathan 2023 Lexicon (Suicide Thoughts/Methods)')) %>%
  mutate(PredictionColumn = dplyr::recode(PredictionColumn,
                                         'Low 2024 Lexicon (Exact)'='Low 2024 Lexicon',
                                         'Swaminathan 2023 Lexicon (Suicide Thoughts/Methods)'='Swaminathan 2023 Lexicon'),
         Metric = dplyr::recode(Metric, 'Recall'='Recall (Sensitivity)', 
                                          'Precision'='Precision (Positive Predictive Value)')) %>%
  ggplot(aes(y = PredictionColumn, x = mean, color = PredictionColumn)) +
  geom_point() +
  geom_errorbarh(aes(xmin = lwr95, xmax = upr95), height = 0.1) +
  geom_line(aes(group = PredictionColumn)) +
  facet_grid(cols = vars(Metric)) +
  theme_bw() +
  labs(x = "Score", y=NULL, 
       title = '\nN=30 PEDSI Participants (Younger Youth with Lower Clinical Acuity)',
       subtitle = paste0("N=", nrow(washu_for_validation), ' labeled text entries with ', 
                         washu_true_positives_n, ' true positives (Base rate ',
                         washu_true_base_rate, '%)')) +
  theme(legend.position = 'none',
        text=element_text(face='bold')) +
  xlim(0, 1) + 
  theme(plot.background = element_rect(color = "black")) +
  scale_color_manual(values = method_colors)


write.csv(performance_metrics_summary_washu, file = '../model_outputs_step1/washu_validation_summary.csv')
```

# Tables of model stats for supplement
```{r}
performance_table_combined = mutate(performance_metrics_summary_combined,
                                outcome = paste0(
                                  format(round(mean, digits = 2), nsmall=2),
                                  ' [',
                                  format(round(lwr95, digits = 2), nsmall=2),
                                  ', ',
                                  format(round(upr95, digits = 2), nsmall=2),
                                  ']'))

performance_table_washu = mutate(performance_metrics_summary_washu,
                                outcome = paste0(
                                  format(round(mean, digits = 2), nsmall=2),
                                  ' [',
                                  format(round(lwr95, digits = 2), nsmall=2),
                                  ', ',
                                  format(round(upr95, digits = 2), nsmall=2),
                                  ']'))

performance_table_washu = performance_table_washu %>%
  dplyr::select(PredictionColumn, Metric, outcome) %>%
  pivot_wider(names_from = 'Metric', values_from = 'outcome', id_cols = 'PredictionColumn') %>%
  mutate(dataset = 'PEDSI')


performance_table_combined = performance_table_combined %>%
  dplyr::select(PredictionColumn, Metric, outcome) %>%
  pivot_wider(names_from = 'Metric', values_from = 'outcome', id_cols = 'PredictionColumn') %>%
  mutate(dataset = 'combined')


model_supplemental_table=rbind(performance_table_combined, performance_table_washu) %>% dplyr::select(-'Sensitivity')
write.csv(model_supplemental_table, file = '../model_outputs_step1/model_stats_supplemental_table_part1_rev1.csv', row.names = FALSE)

```

# Make plot grid figures

```{r}
# smaller plot with fewer models for main figure clarity
validation_plot_small = cowplot::plot_grid(step1_fig_combined_small, step1_fig_pedsi_small,
                                     nrow = 2, align = 'v',
                                     labels = 'Model Performance in Flagging Youth Suicidal Language',
                                     hjust = -.01)

cowplot::save_plot(validation_plot_small, filename = '../figures/main/rev1/step1_validation_plot.png',
                   base_height = 6, base_width = 10)
```

```{r}

```