---
title: "Main Step 2 Analyses of MAPS & PREDICT Flagged Data - Sensitivity Analysis Without Spell-Correction"
author: "Paul Alexander Bloom"
date: "2025-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(purrr)
library(glmmTMB)
library(emmeans)
library(lubridate)
library(ggplot2)
library(ggtext)

maps_predict_colors = c('darkred', '#00BFC4')

```


```{r}
maps_selfreport = read_csv('/Volumes/AUERBACHLAB/Columbia/MAPS_Data/Analysis/Wrangling/Self_Report/data/selfreport_07.11.2024.csv') %>% 
  dplyr::select(ID, age, GROUP, Control, SSI19_i) 

maps = read_csv('../data_stage2/maps_flagged_vs_predict_preproc_2025-08-11_notext.csv')


maps = mutate(maps, flag_bin =
                   ifelse(suicide_lexicon_custom_token == 1 |
                            celeb_historical_suicide_token ==1 |
                            suicide_lexicon_custom_pairs ==1, 1, 0))
maps = maps %>%
  distinct(filepath, tm_message_start, tm_message_end, id_app, .keep_all = TRUE)

maps = dplyr::select(maps,
                            -contains('suicide'),
                            -cat_tz, 
                            -contains('emoji'))

gc()


maps_unique_id = data.frame(filepath=unique(maps$filepath))
maps_unique_id = mutate(maps_unique_id, ID = str_extract(filepath, "(?<=KeyInput/)[^/]+"))

maps = left_join(maps, maps_unique_id, by = 'filepath')
maps = maps %>% dplyr::select(-filepath)

gc()

maps = left_join(maps, maps_selfreport %>% mutate(ID = as.character(ID)), by = 'ID')

by_id_summary = maps %>%
  group_by(ID)%>%
  summarise(total_message = n(),
            total_flagged = sum(flag_bin==1),
            proportion_flagged = total_flagged/total_message)

maps = maps %>%
  group_by(ID)%>%
  mutate(total_message = n()) %>%
  ungroup()


maps = dplyr::filter(maps, total_message > 1000)

sum(maps$flag_bin)
100 *sum(maps$flag_bin) / nrow(maps)

maps_days = maps %>%
  mutate(date = lubridate::date(tm_message_start)) %>%
  group_by(ID, GROUP, Control, SSI19_i, age, date) %>%
  summarise(daily_flagged = sum(flag_bin),
            daily_count = n(), 
            any_daily_flagged = ifelse(daily_flagged > 0, 1, 0)) %>%
  ungroup() %>%
  group_by(ID) %>%
  mutate(total_count = n()) %>%
  ungroup()


unique(maps$id_app[grepl('<null>', maps$id_app)])

maps_app_null = maps %>% dplyr::filter(grepl('<null>', id_app))

nrow(maps_app_null) / nrow(maps)
```

```{r}
m_maps_si <- glmmTMB(
  flag_bin ~ SSI19_i + age + (1 | ID),
  family = binomial(link = "logit"),
  data = dplyr::select(maps, ID, age, SSI19_i, flag_bin) %>% na.omit()
)

m_maps_si_z <- glmmTMB(
  flag_bin ~ SSI19_i + age + (1 | ID),
  family = binomial(link = "logit"),
  data = dplyr::select(maps, ID, age, SSI19_i, flag_bin) %>% na.omit() %>% mutate(SSI19_i = scale(SSI19_i))
)

summary(m_maps_si)
summary(m_maps_si_z)

maps_si_emmeans = emmeans::emmeans(m_maps_si, specs = ~SSI19_i, type = 'response',
                                      at = list(SSI19_i = 0:38)) %>%
  as.data.frame() %>%
  mutate(cohort = 'MAPS')


m_maps_stb <- glmmTMB(
  flag_bin ~ Control + age + (1 | ID),
  family = binomial(link = "logit"),
  data = dplyr::select(maps, ID, age, flag_bin, Control) %>% na.omit()
)

m_maps_stb_days <- glmmTMB(
  any_daily_flagged ~ Control + age + daily_count + total_count + (1 | ID),
  family = binomial(link = "logit"),
  data = maps_days %>% na.omit()
)

summary(m_maps_stb)
summary(m_maps_stb_days)


emm_maps_group_days <- emmeans::emmeans(m_maps_stb_days, ~Control, type = "response") %>%
  as.data.frame() %>%
  mutate(cohort = 'MAPS') %>%
  mutate(GROUP = ifelse(Control ==1, 'Psychiatric Control','STB')) %>%
  dplyr::select(-Control)

emm_maps <- emmeans::emmeans(m_maps_stb, ~Control, type = "response") %>%
  as.data.frame() %>%
  mutate(cohort = 'MAPS') %>%
  mutate(GROUP = ifelse(Control ==1, 'Psychiatric Control','STB')) %>%
  dplyr::select(-Control)

emmeans::emmeans(m_maps_stb, ~Control, type = "response") %>%
  pairs() %>%
  confint()

emmeans::emmeans(m_maps_stb_days, ~Control, type = "response") %>%
  pairs() %>%
  confint()

```


```{r}
predict = read_csv('/Volumes/AUERBACHLAB/Columbia/MAPS_Language/scripts/maps_suicide_lexicon/data_stage2/predict_flagged_vs_maps_preproc_2025-08-11_notext.csv')

predict = mutate(predict, flag_bin =
                   ifelse(suicide_lexicon_custom_token == 1 |
                            celeb_historical_suicide_token ==1 |
                            suicide_lexicon_custom_pairs ==1, 1, 0))

predict = predict %>%
  distinct(filepath, tm_message_start, tm_message_end, id_app, .keep_all = TRUE)

nrow(predict)
sum(predict$flag_bin)
100 *sum(predict$flag_bin) / nrow(predict)


load('/Volumes/AUERBACHLAB/Columbia/SP_Data/Analysis/Wrangling/selfreport/predict_demo_05.22.25.Rda')

table(df$age)

predict_stb = df %>%
  dplyr::select(., 
                ID, gender, orientation, cis, cishet, age, 
                contains('cssrs'),
                group,
                contains('ssi')) %>%
  mutate(lifetime_stb = ifelse(
    cssrsLifetimeMostSevere > 2 | cssrsLifetimeAttempt ==1 |
    cssrsPast2moMostSevere > 2, 1, 0),
    stb_group = case_when(
      lifetime_stb ==1 ~ 'Lifetime STB',
      lifetime_stb ==0 & (group=='MDD' | group=='remMDD') ~ 'Lifetime MDD',
      lifetime_stb ==0 & group=='HC' ~ 'HC',
    )
  ) %>%
  dplyr::select(-contains('cssrs'))

predict = dplyr::select(predict,
                            -contains('suicide'),
                            -cat_tz,
                            -contains('emoji'))

table(predict_stb$stb_group)

predict_unique_id = data.frame(filepath=unique(predict$filepath))
predict_unique_id = mutate(predict_unique_id, ID = str_extract(filepath, "(?<=PREDICT/)[^/]+"))

predict = left_join(predict, predict_unique_id, by = 'filepath')

predict = left_join(predict, predict_stb, by = 'ID')

predict_demo = dplyr::filter(df, ID %in% predict$ID)



predict_app_null = predict %>% dplyr::filter(grepl('<null>', id_app))

nrow(predict_app_null) / nrow(predict)
```


```{r}
predict = predict %>%
  group_by(ID)%>%
  mutate(total_message = n()) %>%
  ungroup()


predict = dplyr::filter(predict, total_message > 1000)

predict_days = predict %>%
  mutate(date = lubridate::date(tm_message_start)) %>%
  group_by(ID, group, stb_group, SSI19_total_i, age, lifetime_stb, date) %>%
  summarise(daily_flagged = sum(flag_bin),
            daily_count = n(), 
            any_daily_flagged = ifelse(daily_flagged > 0, 1, 0)) %>%
  ungroup() %>%
  group_by(ID) %>%
  mutate(total_count = n()) %>%
  ungroup()
```


```{r}
m_predict_si <- glmmTMB(
  flag_bin ~ SSI19_total_i + age + (1 | ID),
  family = binomial(link = "logit"),
  data = dplyr::select(predict, ID, age, SSI19_total_i, flag_bin) %>% na.omit()
)

m_predict_si_days <- glmmTMB(
  any_daily_flagged ~ SSI19_total_i + age + daily_count + total_count + (1 | ID),
  family = binomial(link = "logit"),
  data = predict_days %>% na.omit()
)


m_predict_si_z <- glmmTMB(
  flag_bin ~ SSI19_total_i + age + (1 | ID),
  family = binomial(link = "logit"),
  data = dplyr::select(predict, ID, age, SSI19_total_i, flag_bin) %>% na.omit() %>% mutate(SSI19_total_i = scale(SSI19_total_i))
)

summary(m_predict_si_days)
summary(m_predict_si)
summary(m_predict_si_z)

broom.mixed::tidy(m_predict_si_z, exponentiate=FALSE, conf.int=TRUE)


maps_si_or = broom.mixed::tidy(m_maps_si_z, exponentiate=TRUE, conf.int=TRUE) %>%
  dplyr::filter(term == 'SSI19_i')

maps_si_or_string = paste0('OR=',
                           round(maps_si_or$estimate, 2),
                           ' 95% CI [',
                           round(maps_si_or$conf.low, 2),
                           ', ',
                           round(maps_si_or$conf.high, 2),
                           ']')

predict_si_or = broom.mixed::tidy(m_predict_si_z, exponentiate=TRUE, conf.int=TRUE) %>%
  dplyr::filter(term == 'SSI19_total_i')

predict_si_or_string = paste0('OR=',
                           round(predict_si_or$estimate, 2),
                           ' 95% CI [',
                           round(predict_si_or$conf.low, 2),
                           ', ',
                           round(predict_si_or$conf.high, 2),
                           ']')

si_or_strings = data.frame(cohort = c('MAPS', 'PREDICT'),
                           or_string = c(maps_si_or_string, predict_si_or_string),
                           y = c(13, 11))


predict_si_emmeans = emmeans::emmeans(m_predict_si, specs = ~SSI19_total_i, type = 'response',
                                      at = list(SSI19_total_i = 0:38)) %>%
  as.data.frame() %>%
  mutate(cohort = 'PREDICT') 

predict_si_emmeans_days = emmeans::emmeans(m_predict_si_days, specs = ~SSI19_total_i, type = 'response',
                                      at = list(SSI19_total_i = 0:38)) %>%
  as.data.frame() %>%
  mutate(cohort = 'PREDICT') %>%
  dplyr::rename(., 'SSI19_i'='SSI19_total_i')

predict_si_emmeans = predict_si_emmeans %>%
  dplyr::rename(., 'SSI19_i'='SSI19_total_i')


maps_si_summary = maps %>%
  group_by(ID, SSI19_i) %>%
  summarise(prob = sum(flag_bin)/n(), count = n()) %>%
  mutate(cohort = 'MAPS')

predict_si_summary = predict %>%
  group_by(ID, SSI19_total_i) %>%
  summarise(prob = sum(flag_bin)/n(), count = n()) %>%
  dplyr::select(SSI19_i=SSI19_total_i, everything()) %>%
  mutate(cohort = 'PREDICT')

predict_si_summary_days = predict_days %>%
  group_by(ID, SSI19_total_i) %>%
  summarise(prob = sum(any_daily_flagged)/n(), count = n()) %>%
  dplyr::select(SSI19_i=SSI19_total_i, everything()) %>%
  mutate(cohort = 'PREDICT')

maps_si_summary_days = maps_days %>%
  group_by(ID, SSI19_i) %>%
  summarise(prob = sum(any_daily_flagged)/n(), count = n()) %>%
  mutate(cohort = 'MAPS')

si_emmeans = rbind(predict_si_emmeans, maps_si_emmeans) %>% dplyr::filter(SSI19_i <= 32)


si_plt = ggplot(data = si_emmeans, aes(x = SSI19_i, y = prob*1000)) +
  geom_point(data = predict_si_summary, aes(color = cohort), alpha = 0.5) +
  geom_point(data = maps_si_summary, aes(color = cohort), alpha = 0.5) +
  geom_line(aes(color = cohort), lwd = 2) +
  geom_ribbon(aes(ymin = asymp.LCL*1000, ymax = asymp.UCL*1000, fill = cohort), alpha = 0.2) +
  labs(y = 'Rate of Text Flagged as Suicide-Related\nPer 1000 Entries',
       x = 'Baseline Suicidal Ideation (Beck SSI Self-Report)',
       title = 'Flagged Suicidal Language\nAs a Function of Baseline Suicidal Ideation Severity',
       color = 'Cohort', fill = 'Cohort') +
  theme_bw()

si_summary_combined = rbind(maps_si_summary, predict_si_summary)





```

```{r}
m_predict_stb <- glmmTMB(
  flag_bin ~ lifetime_stb + age + (1 | ID),
  family = binomial(link = "logit"),
  data = dplyr::select(predict, ID, age, lifetime_stb, flag_bin) %>% mutate(lifetime_stb = as.factor(lifetime_stb)) %>% na.omit()
)

summary(m_predict_stb)
```


```{r}
m_predict_group <- glmmTMB(
  flag_bin ~ stb_group + age + (1 | ID),
  family = binomial(link = "logit"),
  data = dplyr::select(predict, ID, age, stb_group, flag_bin) %>% na.omit()
)

m_predict_group_days <- glmmTMB(
  any_daily_flagged ~ stb_group + age + (1 | ID),
  family = binomial(link = "logit"),
  data = predict_days %>% na.omit()
)

summary(m_predict_group_days) 

summary(m_predict_group)

emm_predict <- emmeans(m_predict_group, ~ stb_group, type = "response") %>%
  as.data.frame() %>%
  mutate(cohort = 'PREDICT')

emm_predict_stb <- emmeans(m_predict_stb, ~lifetime_stb, type = "response") %>%
  as.data.frame() %>%
  mutate(cohort = 'PREDICT') %>%
  dplyr::rename(., 'GROUP'='lifetime_stb') %>%
  mutate(GROUP = ifelse(GROUP==1, 'Lifetime STB', 'No STB')) 



emm_predict_days <- emmeans(m_predict_group_days, ~ stb_group, type = "response") %>%
  as.data.frame() %>%
  mutate(cohort = 'PREDICT') %>%
  dplyr::rename(., 'GROUP'='stb_group')

emmeans(m_predict_group, ~ stb_group, type = "response") %>%
  pairs(reverse=TRUE) %>%
  confint()

emmeans(m_predict_group_days, ~ stb_group, type = "response") %>%
  pairs(reverse=TRUE) %>%
  confint()

emmeans(m_maps_stb,  ~Control, type = "response") %>%
  pairs()


emm_predict = emm_predict %>%
  dplyr::rename(., 'GROUP'='stb_group')


group_emmeans_all = rbind(emm_predict, emm_maps) 
group_emmeans_stb = rbind(emm_predict_stb, emm_maps) %>%
  mutate(GROUP = case_when(GROUP == 'STB' ~ 'Lifetime STB',
                           GROUP == 'Psychiatric Control' ~ 'No STB',
                           TRUE ~ GROUP))

group_plt = ggplot(group_emmeans_all, aes(x = GROUP, y = prob*1000, color = cohort)) +
  geom_point() +
  geom_errorbar(aes(ymin = asymp.LCL*1000, ymax = asymp.UCL*1000), width = 0.1) +
  facet_grid(cols = vars(cohort), scales = 'free_x', drop = TRUE) +
  labs(y = 'Rate of Text Flagged as Suicide-Related\nPer 1000 Entries',
       title = 'Flagged Suicidal Language\nAs a Function of Lifetime STB History') +
  theme_bw() +
  theme(legend.position = 'none')



```


```{r}
# Main figure
predict_stb_or = emmeans(m_predict_stb, ~lifetime_stb, type = "response") %>%
  pairs(reverse=TRUE) %>%
  confint()

maps_stb_or = emmeans(m_maps_stb, ~Control, type = "response") %>%
  pairs() %>%
  confint()



maps_stb_or_string = paste0('OR=',
                           format(round(maps_stb_or$odds.ratio, 2), nsmall=2),
                           ' 95% CI [',
                           round(maps_stb_or$asymp.LCL, 2),
                           ', ',
                           round(maps_stb_or$asymp.UCL, 2),
                           ']')

predict_stb_or_string = paste0('OR=',
                           format(round(predict_stb_or$odds.ratio, 2), nsmall=2),
                           ' 95% CI [',
                           round(predict_stb_or$asymp.LCL, 2),
                           ', ',
                           round(predict_stb_or$asymp.UCL, 2),
                           ']')

stb_or_strings = data.frame(cohort = c('MAPS', 'PREDICT'),
                           or_string = c(maps_stb_or_string, predict_stb_or_string),
                           y = c(4, 3.7))


si_or_strings = data.frame(cohort = c('MAPS', 'PREDICT'),
                           or_string = c(maps_si_or_string, predict_si_or_string),
                           y = c(18, 16))


group_plt_stb_main = ggplot(group_emmeans_stb, aes(x = GROUP, y = prob*1000, color = cohort)) +
  geom_point(position = position_dodge(0.2), size = 2) +
  geom_line(aes(group = cohort), position = position_dodge(0.2), lwd =1) +
  geom_label(data = stb_or_strings, aes(x = 1.75, y = y, label = or_string, color = cohort), show.legend = FALSE) +
  geom_errorbar(aes(ymin = asymp.LCL*1000, ymax = asymp.UCL*1000), width = 0.1, position = position_dodge(0.2),
                lwd = 1) +
  labs(y = 'Suicidal Language Frequency\nPer 1000 Entries',
       x = 'Group',
       color = 'Cohort') +
  theme_bw() +
  theme(legend.position = 'right') +
  guides(label = 'none') +
  scale_color_manual(values=maps_predict_colors)

si_plt_main = ggplot(data = si_emmeans, aes(x = SSI19_i, y = prob*1000)) +
  geom_point(data = predict_si_summary, aes(color = cohort), alpha = 0.5) +
  geom_point(data = maps_si_summary, aes(color = cohort), alpha = 0.5) +
  geom_label(data = si_or_strings, aes(x = 15, y = y, label = or_string, color = cohort)) +
  geom_line(aes(color = cohort), lwd = 2) +
  geom_ribbon(aes(ymin = asymp.LCL*1000, ymax = asymp.UCL*1000, fill = cohort), alpha = 0.2) +
  labs(y = 'Suicidal Language Frequency\nPer 1000 Entries',
       x = 'Reported Baseline Suicidal Ideation',
       color = 'Cohort', fill = 'Cohort') +
  theme_bw() +
  theme(legend.position = 'none') +
  scale_color_manual(values=maps_predict_colors)

main_panel = cowplot::plot_grid(group_plt_stb_main, si_plt_main, nrow = 1, labels = c('A', 'B'),
                             align = 'h', axis = 'bt', rel_widths = c(1.3, 1))
cowplot::save_plot(main_panel, filename = '../figures/supplemental/maps_predict_stb_history_nospellcorrect.png',
                   base_height = 5, base_width = 8.5)
```


```{r}

```
