---
title: "Main Step 2 Analyses of MAPS & PREDICT Flagged Data"
author: "Paul Alexander Bloom"
date: "2025-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(purrr)
library(glmmTMB)
library(emmeans)
library(lubridate)
library(ggplot2)
library(ggtext)

maps_predict_colors = c('darkred', '#00BFC4')
```

# Load in MAPS data

```{r}
maps_selfreport = read_csv('/Volumes/AUERBACHLAB/Columbia/MAPS_Data/Analysis/Wrangling/Self_Report/data/selfreport_07.11.2024.csv') %>% 
  dplyr::select(ID, age, GROUP, Control, SSI19_i) 

maps = read_csv('../data_stage2/maps_flagged_vs_predict_final_2025-07-28.csv')

# Code lexicon flagging
maps = mutate(maps, flag_bin =
                   ifelse(suicide_lexicon_custom_token == 1 |
                            celeb_historical_suicide_token ==1 |
                            suicide_lexicon_custom_pairs ==1, 1, 0))
# Make sure no duplicates
maps = maps %>%
  distinct(filepath, corrected_message, tm_message_start, tm_message_end, id_app, .keep_all = TRUE)

maps = dplyr::select(maps,
                            -contains('suicide'),
                            -cat_tz,
                            -contains('emoji'))

gc()

# Code IDs from filepaths
maps_unique_id = data.frame(filepath=unique(maps$filepath))
maps_unique_id = mutate(maps_unique_id, ID = str_extract(filepath, "(?<=KeyInput/)[^/]+"))

maps = left_join(maps, maps_unique_id, by = 'filepath')
maps = maps %>% dplyr::select(-filepath)

gc()
```



# MAPS Data Cleaning / Prep for Models

```{r}
maps = left_join(maps, maps_selfreport %>% mutate(ID = as.character(ID)), by = 'ID')
```

### Make sure not to include any excluded MAPS participants
```{r}
maps_inclusion = read_csv('/Volumes/AUERBACHLAB/Columbia/MAPS_Data/Analysis/ID_FINAL/id_list_compiled_2026-02-10.csv')


maps_include_ids = maps_inclusion %>%
  dplyr::filter(!is.na(study_id), !grepl('ineligible', notes_main_idlist), !grepl('not eligible', notes_main_idlist))


removed_ids = dplyr::filter(maps, !ID %in% maps_include_ids$study_id)

maps = dplyr::filter(maps, ID %in% maps_include_ids$study_id)


```


```{r}
# filter out participants with under 1000 entries
maps = maps %>%
  group_by(ID)%>%
  mutate(total_message = n()) %>%
  ungroup()


maps = dplyr::filter(maps, total_message >= 1000)

maps_days = maps %>%
  mutate(date = lubridate::date(tm_message_start)) %>%
  group_by(ID, GROUP, Control, SSI19_i, age, date, total_message) %>%
  summarise(daily_flagged = sum(flag_bin),
            daily_count = n(), 
            any_daily_flagged = ifelse(daily_flagged > 0, 1, 0),
            daily_flag_pct = 100*daily_flagged/daily_count) %>%
  ungroup() %>%
  group_by(ID) %>%
  mutate(
         lifetime_stb = ifelse(Control==0, 1, 0)) %>%
  ungroup() %>%
  mutate(SSI19_i_z = scale(SSI19_i))
```
# Negative binomial models to parallel main models

```{r}
m_maps_stb_days_nbinom <- glmmTMB(
  daily_flagged ~ lifetime_stb + age + offset(log(daily_count)) + total_message + (1 | ID),
  family = nbinom2(link = "log"),
  data = maps_days %>% na.omit()
)

m_maps_si_days_nbinom <- glmmTMB(
  daily_flagged ~ SSI19_i_z + age + offset(log(daily_count)) + total_message + (1 | ID),
  family = nbinom2(link = "log"),
  data = maps_days %>% na.omit()
)

summary(m_maps_stb_days_nbinom)
summary(m_maps_si_days_nbinom)

# To get IRRs
broom.mixed::tidy(m_maps_stb_days_nbinom, conf.int=TRUE, exponentiate=TRUE)
broom.mixed::tidy(m_maps_si_days_nbinom, conf.int=TRUE, exponentiate=TRUE)

```
# MAPS Time of Day

```{r}
maps = mutate(maps, hour = hour(ymd_hms(tm_message_start)),
                timebin = case_when(
                  hour < 3 ~ 'Night\n(Midnight-3AM)',
                  hour >=3 & hour < 6 ~ 'Early Morning\n(3-6AM)',
                  hour >= 6 & hour < 9 ~ 'Morning\n(6-9AM)',
                  hour >= 9 & hour < 12 ~ 'Late Morning\n(9AM-Noon)',
                  hour >= 12 & hour < 15 ~ 'Early Afternoon\n(Noon-3pm)',
                  hour >=15 & hour < 18 ~ 'Late Afternoon\n(3-6pm)',
                  hour >= 18 & hour < 21 ~ 'Evening\n(6-9PM)',
                  hour >= 21 ~ 'Night\n(9PM-Midnight)')
                )


timebin_levels <- c(
  'Night\n(Midnight-3AM)',
  'Early Morning\n(3-6AM)',
  'Morning\n(6-9AM)',
  'Late Morning\n(9AM-Noon)',
  'Early Afternoon\n(Noon-3pm)',
  'Late Afternoon\n(3-6pm)',
  'Evening\n(6-9PM)',
  'Night\n(9PM-Midnight)'
)

timecount = maps %>%
  group_by(ID, timebin) %>%
  count()

all_timebins <- unique(maps$timebin)


maps_time_for_nbinom = maps %>%
  mutate(date = lubridate::date(tm_message_start)) %>%
  group_by(ID, GROUP, Control, SSI19_i, age, timebin, date) %>%
  summarise(
    timebin_flagged = sum(flag_bin),
    timebin_count = n(),
  ) %>%
  ungroup() %>%
  group_by(ID) %>%
  mutate(
    total_count = n(),
    lifetime_stb = ifelse(Control == 0, 1, 0)
  ) %>%
  ungroup() %>%
  mutate(
    SSI19_i_z = scale(SSI19_i)
  )


m_maps_timebin_nbinom <- glmmTMB(
  timebin_flagged ~ timebin + age + offset(log(timebin_count)) + total_count + (1 | ID),
  family = nbinom2(link = "log"),
  data = maps_time_for_nbinom %>% na.omit()
)

summary(m_maps_timebin_nbinom)

timeofday_emmeans_maps = emmeans::emmeans(m_maps_timebin_nbinom, specs = 'timebin', type = 'response') %>%
  data.frame()

time_of_day_maps_nbinom_plot = timeofday_emmeans_maps %>%
  ggplot(data = ., aes(x = timebin, y = response)) +
  geom_point() +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.1) +
  labs(y = 'Expected Mean Rate of Flagged Text\nPer 3-Hour Bin on a Given Day',
       title = 'maps') +
  theme_bw()

```

# PREDICT


Loading in PREDICT Data
```{r}
predict = read_csv('../data_stage2/predict_flagged_vs_maps_final_2025-08-11.csv')

predict = mutate(predict, flag_bin =
                   ifelse(suicide_lexicon_custom_token == 1 |
                            celeb_historical_suicide_token ==1 |
                            suicide_lexicon_custom_pairs ==1, 1, 0))

predict = predict %>%
  distinct(corrected_message, tm_message_start, tm_message_end, id_app, filepath, .keep_all = TRUE)

nrow(predict)

# what proportion of predict entries were flagged?
predict_n = nrow(predict)
sum_predict_flagged = sum(predict$flag_bin)
pct_predict_flaggged = 100 *sum(predict$flag_bin) / nrow(predict)


load('/Volumes/AUERBACHLAB/Columbia/SP_Data/Analysis/Wrangling/Self_Report/predict_demo_01.05.26.Rda')

table(df$age)

predict_stb = df %>%
  dplyr::select(., 
                ID, gender, orientation, cis, cishet, age, 
                contains('cssrs'),
                group,
                contains('ssi')) %>%
  mutate(lifetime_stb = ifelse(
    cssrsLifetimeMostSevere > 2 | cssrsLifetimeAttempt ==1 |
    cssrsPast2moMostSevere > 2, 1, 0),
    lifetime_stb = ifelse(
     is.na(lifetime_stb) & SSI21_total_i == 0, 0, lifetime_stb
    ),
    stb_group = case_when(
      lifetime_stb ==1 ~ 'Lifetime STB',
      lifetime_stb ==0 & (group=='MDD' | group=='remMDD') ~ 'Lifetime MDD',
      lifetime_stb ==0 & group=='HC' ~ 'HC',
    ),
    recent_active_ideation = ifelse(cssrsPast2moMostSevere > 2, 1, 0)
  ) %>%
  dplyr::select(-contains('cssrs'))

predict = dplyr::select(predict,
                            -contains('suicide'),
                            -cat_tz,
                            -contains('emoji'))

predict_stb_nona = predict_stb %>% dplyr::filter(!is.na(lifetime_stb)) 

predict_stb_nona %>%
  group_by(lifetime_stb) %>%
  summarise(pct = n()/nrow(predict_stb_nona))

predict_stb_nona %>%
  group_by(recent_active_ideation) %>%
  summarise(pct = n()/nrow(predict_stb_nona))

table(predict_stb_nona$group) / nrow(predict_stb_nona)

predict_unique_id = data.frame(filepath=unique(predict$filepath))
predict_unique_id = mutate(predict_unique_id, ID = str_extract(filepath, "(?<=PREDICT/)[^/]+"))

predict = left_join(predict, predict_unique_id, by = 'filepath')

predict = left_join(predict, predict_stb, by = 'ID')


predict_demo = dplyr::filter(df, ID %in% predict$ID)

```

# PREDICT Data Cleaning / Prep for Models

```{r}
predict = predict %>%
  group_by(ID)%>%
  mutate(total_message = n()) %>%
  ungroup()

# filter out predict participants with under 1000 entries
predict = dplyr::filter(predict, total_message >= 1000)

predict_days = predict %>%
  ungroup() %>%
  mutate(date = lubridate::date(tm_message_start)) %>%
  group_by(ID, group, stb_group, SSI19_total_i, age, lifetime_stb, date, total_message) %>%
  summarise(daily_flagged = sum(flag_bin),
            daily_count = n(), 
            any_daily_flagged = ifelse(daily_flagged > 0, 1, 0),
            daily_flag_pct = 100*sum(daily_flagged)/daily_count) %>%
  ungroup() %>%
  mutate(SSI19_i_z = scale(SSI19_total_i)) 

gc()
```
# Negative binomial models to parallel main models

```{r}
m_predict_stb_days_nbinom <- glmmTMB(
  daily_flagged ~ lifetime_stb + age + offset(log(daily_count)) + total_message + (1 | ID),
  family = nbinom2(link = "log"),
  data = predict_days %>% na.omit()
)

m_predict_si_days_nbinom <- glmmTMB(
  daily_flagged ~ SSI19_i_z + age + offset(log(daily_count)) + total_message + (1 | ID),
  family = nbinom2(link = "log"),
  data = predict_days %>% na.omit()
)

summary(m_predict_stb_days_nbinom)
summary(m_predict_si_days_nbinom)

# To get IRRs
broom.mixed::tidy(m_predict_stb_days_nbinom, conf.int=TRUE, exponentiate=TRUE)
broom.mixed::tidy(m_predict_si_days_nbinom, conf.int=TRUE, exponentiate=TRUE)

```


# Time of Day 
```{r}
predict = mutate(predict, hour = hour(ymd_hms(tm_message_start)),
                timebin = case_when(
                  hour < 3 ~ 'Night\n(Midnight-3AM)',
                  hour >=3 & hour < 6 ~ 'Early Morning\n(3-6AM)',
                  hour >= 6 & hour < 9 ~ 'Morning\n(6-9AM)',
                  hour >= 9 & hour < 12 ~ 'Late Morning\n(9AM-Noon)',
                  hour >= 12 & hour < 15 ~ 'Early Afternoon\n(Noon-3pm)',
                  hour >=15 & hour < 18 ~ 'Late Afternoon\n(3-6pm)',
                  hour >= 18 & hour < 21 ~ 'Evening\n(6-9PM)',
                  hour >= 21 ~ 'Night\n(9PM-Midnight)')
                )



predict_time_for_nbinom = predict %>%
  mutate(date = lubridate::date(tm_message_start)) %>%
  group_by(ID, age, timebin, date) %>%
  summarise(
    timebin_flagged = sum(flag_bin),
    timebin_count = n(),
  ) %>%
  ungroup() %>%
  group_by(ID) %>%
  mutate(
    total_count = n(),
  ) %>%
  ungroup()


m_predict_timebin_nbinom <- glmmTMB(
  timebin_flagged ~ timebin + age + offset(log(timebin_count)) + total_count + (1 | ID),
  family = nbinom2(link = "log"),
  data = predict_time_for_nbinom %>% na.omit()
)

summary(m_predict_timebin_nbinom)

timeofday_emmeans_predict = emmeans::emmeans(m_predict_timebin_nbinom, specs = 'timebin', type = 'response') %>%
  data.frame()

```

# Combined Negative Binomial Time-of-Day Plot

```{r}
timeofday_emmeans_predict$timebin <- factor(timeofday_emmeans_predict$timebin, levels = timebin_levels)

time_of_day_all = rbind(timeofday_emmeans_maps %>% mutate(cohort = 'MAPS'),
                        timeofday_emmeans_predict %>% mutate(cohort = 'PREDICT'))

time_of_day_all$timebin <- factor(time_of_day_all$timebin, levels = timebin_levels)



time_of_day_combined = time_of_day_all %>%
  ggplot(data = ., aes(x = timebin, y = response, color = cohort)) +
  geom_point(position = position_dodge(0.1)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.1,
                position = position_dodge(0.1)) +
  labs(y = 'Rate of Flagged Text by Time of Day\nNegative Binomial Regression',
       title = 'Expected Mean Rate of Flagged Text\nPer 3-Hour Bin on a Given Day',
       x = 'Time of Day', color = 'Cohort') +
  theme_bw() +
  theme(legend.position = 'bottom',
        text = element_text(face='bold')) +
  scale_color_manual(values=maps_predict_colors)

ggsave(time_of_day_combined, file = '../figures/supplemental/rev1_added/time_of_day_negative_binomial.png',
       height = 6, width = 10)
```


```{r}

```
